version: "3"

services:
  server:
    ports:
      - "3000:3000"
    build: ./server
    depends_on:
      - influxdb
    volumes:
      - ./server:/go/src
      
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DB=monitor
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/influxdb-meta.conf:/etc/influxdb/influxdb-meta.conf