version: "3"

services:
  server:
    ports:
      - "80:3000"
    image: glena/electric-monitor-server
    environment:
      - PORT=3000
      - HOST=http://influxdb:8086
      - DB_name=monitor
      - DB_USER=user
      - DB_PASSWORD=
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    config: /etc/influxdb/influxdb.conf
    volumes:
      - /root/settings/influxdb/data:/var/lib/influxdb
      - /data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
      - INFLUXDB_REPORTING_DISABLED=false 
      - INFLUXDB_HTTP_AUTH_ENABLED=true 
      - INFLUXDB_DB=monitor 
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=
      - INFLUXDB_USER=user 
      - INFLUXDB_USER_PASSWORD=
